(in-package :tsumeli)

(defun main()
  (let* ((config (read-config))
	 (full-board (getf config :full-board))
	 (n (getf config :turns))
	 (depth (getf config :depth))
	 (evaluation-function (getf config :evaluation-function))
	 (algorithm (getf config :algorithm)))
    (format-game full-board)
    (time (start full-board n evaluation-function algorithm depth)))
  (read))
